branch-defaults:
  production:
    environment: milk-meets-cookie-dev
    group_suffix: null
global:
  application_name: milk_meets_cookie
  branch: null
  default_platform: Node.js
  default_region: us-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
