export default [
  { name: 'Alabama',
    children:
     [ 'Auburn',
       'Birmingham',
       'Decatur',
       'Dothan',
       'Florence',
       'Hoover',
       'Huntsville',
       'Madison',
       'Mobile',
       'Montgomery',
       'Phenix City',
       'Tuscaloosa' ] },
  { name: 'Alaska', children: [ 'Anchorage' ] },
  { name: 'Arizona',
    children:
     [ 'Apache Junction',
       'Avondale',
       'Buckeye',
       'Bullhead City',
       'Casa Grande',
       'Chandler',
       'Flagstaff',
       'Gilbert',
       'Glendale',
       'Goodyear',
       'Lake Havasu City',
       'Marana',
       'Maricopa',
       'Mesa',
       'Oro Valley',
       'Peoria',
       'Phoenix',
       'Prescott',
       'Prescott Valley',
       'Scottsdale',
       'Sierra Vista',
       'Surprise',
       'Tempe',
       'Tucson',
       'Yuma' ] },
  { name: 'Arkansas',
    children:
     [ 'Bentonville',
       'Conway',
       'Fayetteville',
       'Fort Smith',
       'Jonesboro',
       'Little Rock',
       'North Little Rock',
       'Pine Bluff',
       'Rogers',
       'Springdale' ] },
  { name: 'California',
    children:
     [ 'Alameda',
       'Alhambra',
       'Aliso Viejo',
       'Anaheim',
       'Antioch',
       'Apple Valley',
       'Arcadia',
       'Azusa',
       'Bakersfield',
       'Baldwin Park',
       'Beaumont',
       'Bell Gardens',
       'Bellflower',
       'Berkeley',
       'Brea',
       'Brentwood',
       'Buena Park',
       'Burbank',
       'Calexico',
       'Camarillo',
       'Campbell',
       'Carlsbad',
       'Carson',
       'Cathedral City',
       'Ceres',
       'Cerritos',
       'Chico',
       'Chino',
       'Chino Hills',
       'Chula Vista',
       'Citrus Heights',
       'Clovis',
       'Coachella',
       'Colton',
       'Compton',
       'Concord',
       'Corona',
       'Costa Mesa',
       'Covina',
       'Culver City',
       'Cupertino',
       'Cypress',
       'Daly City',
       'Danville',
       'Davis',
       'Delano',
       'Diamond Bar',
       'Downey',
       'Dublin',
       'Eastvale',
       'El Cajon',
       'El Centro',
       'El Monte',
       'Elk Grove',
       'Encinitas',
       'Escondido',
       'Fairfield',
       'Folsom',
       'Fontana',
       'Fountain Valley',
       'Fremont',
       'Fresno',
       'Fullerton',
       'Garden Grove',
       'Gardena',
       'Gilroy',
       'Glendale',
       'Glendora',
       'Hanford',
       'Hawthorne',
       'Hayward',
       'Hemet',
       'Hesperia',
       'Highland',
       'Huntington Beach',
       'Huntington Park',
       'Indio',
       'Inglewood',
       'Irvine',
       'Jurupa Valley',
       'La Habra',
       'La Mesa',
       'La Mirada',
       'La Puente',
       'La Quinta',
       'Laguna Niguel',
       'Lake Elsinore',
       'Lake Forest',
       'Lakewood',
       'Lancaster',
       'Lincoln',
       'Livermore',
       'Lodi',
       'Lompoc',
       'Long Beach',
       'Los Angeles',
       'Lynwood',
       'Madera',
       'Manteca',
       'Martinez',
       'Menifee',
       'Merced',
       'Milpitas',
       'Mission Viejo',
       'Modesto',
       'Monrovia',
       'Montclair',
       'Montebello',
       'Monterey Park',
       'Moreno Valley',
       'Morgan Hill',
       'Mountain View',
       'Murrieta',
       'Napa',
       'National City',
       'Newark',
       'Newport Beach',
       'Norwalk',
       'Novato',
       'Oakland',
       'Oakley',
       'Oceanside',
       'Ontario',
       'Orange',
       'Oxnard',
       'Pacifica',
       'Palm Desert',
       'Palm Springs',
       'Palmdale',
       'Palo Alto',
       'Paramount',
       'Pasadena',
       'Perris',
       'Petaluma',
       'Pico Rivera',
       'Pittsburg',
       'Placentia',
       'Pleasanton',
       'Pomona',
       'Porterville',
       'Poway',
       'Rancho Cordova',
       'Rancho Cucamonga',
       'Rancho Palos Verdes',
       'Rancho Santa Margarita',
       'Redding',
       'Redlands',
       'Redondo Beach',
       'Redwood City',
       'Rialto',
       'Richmond',
       'Riverside',
       'Rocklin',
       'Rohnert Park',
       'Rosemead',
       'Roseville',
       'Sacramento',
       'Salinas',
       'San Bernardino',
       'San Bruno',
       'San Buenaventura (Ventura)',
       'San Clemente',
       'San Diego',
       'San Francisco',
       'San Gabriel',
       'San Jacinto',
       'San Jose',
       'San Leandro',
       'San Luis Obispo',
       'San Marcos',
       'San Mateo',
       'San Rafael',
       'San Ramon',
       'Santa Ana',
       'Santa Barbara',
       'Santa Clara',
       'Santa Clarita',
       'Santa Cruz',
       'Santa Maria',
       'Santa Monica',
       'Santa Rosa',
       'Santee',
       'Simi Valley',
       'South Gate',
       'South San Francisco',
       'Stanton',
       'Stockton',
       'Sunnyvale',
       'Temecula',
       'Thousand Oaks',
       'Torrance',
       'Tracy',
       'Tulare',
       'Turlock',
       'Tustin',
       'Union City',
       'Upland',
       'Vacaville',
       'Vallejo',
       'Victorville',
       'Visalia',
       'Vista',
       'Walnut Creek',
       'Watsonville',
       'West Covina',
       'West Sacramento',
       'Westminster',
       'Whittier',
       'Woodland',
       'Yorba Linda',
       'Yuba City',
       'Yucaipa' ] },
  { name: 'Colorado',
    children:
     [ 'Arvada',
       'Aurora',
       'Boulder',
       'Broomfield',
       'Castle Rock',
       'Centennial',
       'Colorado Springs',
       'Commerce City',
       'Denver',
       'Fort Collins',
       'Grand Junction',
       'Greeley',
       'Lakewood',
       'Littleton',
       'Longmont',
       'Loveland',
       'Northglenn',
       'Parker',
       'Pueblo',
       'Thornton',
       'Westminster' ] },
  { name: 'Connecticut',
    children:
     [ 'Bridgeport',
       'Bristol',
       'Danbury',
       'Hartford',
       'Meriden',
       'Middletown',
       'Milford',
       'New Britain',
       'New Haven',
       'Norwalk',
       'Norwich',
       'Shelton',
       'Stamford',
       'Waterbury',
       'West Haven' ] },
  { name: 'Delaware', children: [ 'Dover', 'Wilmington' ] },
  { name: 'District of Columbia', children: [ 'Washington' ] },
  { name: 'Florida',
    children:
     [ 'Altamonte Springs',
       'Apopka',
       'Aventura',
       'Boca Raton',
       'Bonita Springs',
       'Boynton Beach',
       'Bradenton',
       'Cape Coral',
       'Clearwater',
       'Coconut Creek',
       'Coral Gables',
       'Coral Springs',
       'Cutler Bay',
       'Davie',
       'Daytona Beach',
       'Deerfield Beach',
       'Delray Beach',
       'Deltona',
       'Doral',
       'Fort Lauderdale',
       'Fort Myers',
       'Fort Pierce',
       'Gainesville',
       'Greenacres',
       'Hallandale Beach',
       'Hialeah',
       'Hollywood',
       'Homestead',
       'Jacksonville',
       'Jupiter',
       'Kissimmee',
       'Lakeland',
       'Largo',
       'Lauderhill',
       'Margate',
       'Melbourne',
       'Miami',
       'Miami Beach',
       'Miami Gardens',
       'Miramar',
       'North Lauderdale',
       'North Miami',
       'North Miami Beach',
       'North Port',
       'Oakland Park',
       'Ocala',
       'Ocoee',
       'Orlando',
       'Ormond Beach',
       'Palm Bay',
       'Palm Beach Gardens',
       'Palm Coast',
       'Panama City',
       'Pembroke Pines',
       'Pensacola',
       'Pinellas Park',
       'Plantation',
       'Pompano Beach',
       'Port Orange',
       'Port St. Lucie',
       'Sanford',
       'Sarasota',
       'St. Cloud',
       'St. Petersburg',
       'Sunrise',
       'Tallahassee',
       'Tamarac',
       'Tampa',
       'Titusville',
       'Wellington',
       'West Palm Beach',
       'Weston',
       'Winter Garden' ] },
  { name: 'Georgia',
    children:
     [ 'Albany',
       'Alpharetta',
       'Athens-Clarke County',
       'Atlanta',
       'Augusta-Richmond County',
       'Brookhaven',
       'Columbus',
       'Dunwoody',
       'Johns Creek',
       'Macon',
       'Marietta',
       'Peachtree Corners',
       'Roswell',
       'Sandy Springs',
       'Savannah',
       'Smyrna',
       'Valdosta',
       'Warner Robins' ] },
  { name: 'Hawaii', children: [ 'Honolulu' ] },
  { name: 'Idaho',
    children:
     [ 'Boise City',
       'Caldwell',
       'Coeur d\'Alene',
       'Idaho Falls',
       'Meridian',
       'Nampa',
       'Pocatello',
       'Twin Falls' ] },
  { name: 'Illinois',
    children:
     [ 'Addison',
       'Arlington Heights',
       'Aurora',
       'Bartlett',
       'Belleville',
       'Berwyn',
       'Bloomington',
       'Bolingbrook',
       'Buffalo Grove',
       'Calumet City',
       'Carol Stream',
       'Carpentersville',
       'Champaign',
       'Chicago',
       'Cicero',
       'Crystal Lake',
       'DeKalb',
       'Decatur',
       'Des Plaines',
       'Downers Grove',
       'Elgin',
       'Elmhurst',
       'Evanston',
       'Glenview',
       'Hanover Park',
       'Hoffman Estates',
       'Joliet',
       'Lombard',
       'Moline',
       'Mount Prospect',
       'Naperville',
       'Normal',
       'Oak Lawn',
       'Oak Park',
       'Orland Park',
       'Palatine',
       'Park Ridge',
       'Peoria',
       'Plainfield',
       'Quincy',
       'Rock Island',
       'Rockford',
       'Romeoville',
       'Schaumburg',
       'Skokie',
       'Springfield',
       'Streamwood',
       'Tinley Park',
       'Urbana',
       'Waukegan',
       'Wheaton',
       'Wheeling' ] },
  { name: 'Indiana',
    children:
     [ 'Anderson',
       'Bloomington',
       'Carmel',
       'Columbus',
       'Elkhart',
       'Evansville',
       'Fishers',
       'Fort Wayne',
       'Gary',
       'Greenwood',
       'Hammond',
       'Indianapolis',
       'Jeffersonville',
       'Kokomo',
       'Lafayette',
       'Lawrence',
       'Mishawaka',
       'Muncie',
       'Noblesville',
       'South Bend',
       'Terre Haute' ] },
  { name: 'Iowa',
    children:
     [ 'Ames',
       'Ankeny',
       'Cedar Falls',
       'Cedar Rapids',
       'Council Bluffs',
       'Davenport',
       'Des Moines',
       'Dubuque',
       'Iowa City',
       'Sioux City',
       'Urbandale',
       'Waterloo',
       'West Des Moines' ] },
  { name: 'Kansas',
    children:
     [ 'Hutchinson',
       'Kansas City',
       'Lawrence',
       'Lenexa',
       'Manhattan',
       'Olathe',
       'Overland Park',
       'Salina',
       'Shawnee',
       'Topeka',
       'Wichita' ] },
  { name: 'Kentucky',
    children:
     [ 'Bowling Green',
       'Covington',
       'Lexington-Fayette',
       'Louisville/Jefferson County',
       'Owensboro' ] },
  { name: 'Louisiana',
    children:
     [ 'Alexandria',
       'Baton Rouge',
       'Bossier City',
       'Kenner',
       'Lafayette',
       'Lake Charles',
       'Monroe',
       'New Orleans',
       'Shreveport' ] },
  { name: 'Maine', children: [ 'Portland' ] },
  { name: 'Maryland',
    children:
     [ 'Annapolis',
       'Baltimore',
       'Bowie',
       'Frederick',
       'Gaithersburg',
       'Hagerstown',
       'Rockville' ] },
  { name: 'Massachusetts',
    children:
     [ 'Attleboro',
       'Barnstable Town',
       'Beverly',
       'Boston',
       'Brockton',
       'Cambridge',
       'Chelsea',
       'Chicopee',
       'Everett',
       'Fall River',
       'Fitchburg',
       'Haverhill',
       'Holyoke',
       'Lawrence',
       'Leominster',
       'Lowell',
       'Lynn',
       'Malden',
       'Marlborough',
       'Medford',
       'Methuen',
       'New Bedford',
       'Newton',
       'Peabody',
       'Pittsfield',
       'Quincy',
       'Revere',
       'Salem',
       'Somerville',
       'Springfield',
       'Taunton',
       'Waltham',
       'Westfield',
       'Weymouth Town',
       'Woburn',
       'Worcester' ] },
  { name: 'Michigan',
    children:
     [ 'Ann Arbor',
       'Battle Creek',
       'Dearborn',
       'Dearborn Heights',
       'Detroit',
       'East Lansing',
       'Farmington Hills',
       'Flint',
       'Grand Rapids',
       'Kalamazoo',
       'Kentwood',
       'Lansing',
       'Lincoln Park',
       'Livonia',
       'Midland',
       'Muskegon',
       'Novi',
       'Pontiac',
       'Portage',
       'Rochester Hills',
       'Roseville',
       'Royal Oak',
       'Saginaw',
       'Southfield',
       'St. Clair Shores',
       'Sterling Heights',
       'Taylor',
       'Troy',
       'Warren',
       'Westland',
       'Wyoming' ] },
  { name: 'Minnesota',
    children:
     [ 'Apple Valley',
       'Blaine',
       'Bloomington',
       'Brooklyn Park',
       'Burnsville',
       'Coon Rapids',
       'Duluth',
       'Eagan',
       'Eden Prairie',
       'Edina',
       'Lakeville',
       'Mankato',
       'Maple Grove',
       'Maplewood',
       'Minneapolis',
       'Minnetonka',
       'Moorhead',
       'Plymouth',
       'Rochester',
       'Shakopee',
       'St. Cloud',
       'St. Louis Park',
       'St. Paul',
       'Woodbury' ] },
  { name: 'Mississippi',
    children:
     [ 'Biloxi',
       'Gulfport',
       'Hattiesburg',
       'Jackson',
       'Meridian',
       'Southaven' ] },
  { name: 'Missouri',
    children:
     [ 'Blue Springs',
       'Cape Girardeau',
       'Chesterfield',
       'Columbia',
       'Florissant',
       'Independence',
       'Jefferson City',
       'Joplin',
       'Kansas City',
       'Lee\'s Summit',
       'O\'Fallon',
       'Springfield',
       'St. Charles',
       'St. Joseph',
       'St. Louis',
       'St. Peters' ] },
  { name: 'Montana',
    children: [ 'Billings', 'Bozeman', 'Great Falls', 'Missoula' ] },
  { name: 'Nebraska',
    children: [ 'Bellevue', 'Grand Island', 'Lincoln', 'Omaha' ] },
  { name: 'Nevada',
    children:
     [ 'Carson City',
       'Henderson',
       'Las Vegas',
       'North Las Vegas',
       'Reno',
       'Sparks' ] },
  { name: 'New Hampshire',
    children: [ 'Concord', 'Manchester', 'Nashua' ] },
  { name: 'New Jersey',
    children:
     [ 'Atlantic City',
       'Bayonne',
       'Camden',
       'Clifton',
       'East Orange',
       'Elizabeth',
       'Hackensack',
       'Hoboken',
       'Jersey City',
       'Kearny',
       'Linden',
       'New Brunswick',
       'Newark',
       'Passaic',
       'Paterson',
       'Perth Amboy',
       'Plainfield',
       'Sayreville',
       'Trenton',
       'Union City',
       'Vineland',
       'West New York' ] },
  { name: 'New Mexico',
    children:
     [ 'Albuquerque',
       'Clovis',
       'Farmington',
       'Las Cruces',
       'Rio Rancho',
       'Roswell',
       'Santa Fe' ] },
  { name: 'New York',
    children:
     [ 'Albany',
       'Binghamton',
       'Buffalo',
       'Freeport',
       'Hempstead',
       'Mount Vernon',
       'New Rochelle',
       'New York',
       'Niagara Falls',
       'Rochester',
       'Schenectady',
       'Syracuse',
       'Troy',
       'Utica',
       'Valley Stream',
       'White Plains',
       'Yonkers' ] },
  { name: 'North Carolina',
    children:
     [ 'Apex',
       'Asheville',
       'Burlington',
       'Cary',
       'Chapel Hill',
       'Charlotte',
       'Concord',
       'Durham',
       'Fayetteville',
       'Gastonia',
       'Greensboro',
       'Greenville',
       'Hickory',
       'High Point',
       'Huntersville',
       'Jacksonville',
       'Kannapolis',
       'Raleigh',
       'Rocky Mount',
       'Wilmington',
       'Wilson',
       'Winston-Salem' ] },
  { name: 'North Dakota',
    children: [ 'Bismarck', 'Fargo', 'Grand Forks', 'Minot' ] },
  { name: 'Ohio',
    children:
     [ 'Akron',
       'Beavercreek',
       'Canton',
       'Cincinnati',
       'Cleveland',
       'Cleveland Heights',
       'Columbus',
       'Cuyahoga Falls',
       'Dayton',
       'Dublin',
       'Elyria',
       'Euclid',
       'Fairfield',
       'Findlay',
       'Grove City',
       'Hamilton',
       'Huber Heights',
       'Kettering',
       'Lakewood',
       'Lancaster',
       'Lima',
       'Lorain',
       'Mansfield',
       'Mentor',
       'Middletown',
       'Newark',
       'Parma',
       'Springfield',
       'Strongsville',
       'Toledo',
       'Warren',
       'Westerville',
       'Youngstown' ] },
  { name: 'Oklahoma',
    children:
     [ 'Broken Arrow',
       'Edmond',
       'Enid',
       'Lawton',
       'Midwest City',
       'Moore',
       'Muskogee',
       'Norman',
       'Oklahoma City',
       'Stillwater',
       'Tulsa' ] },
  { name: 'Oregon',
    children:
     [ 'Albany',
       'Beaverton',
       'Bend',
       'Corvallis',
       'Eugene',
       'Gresham',
       'Hillsboro',
       'Keizer',
       'Lake Oswego',
       'Medford',
       'Portland',
       'Salem',
       'Springfield',
       'Tigard' ] },
  { name: 'Pennsylvania',
    children:
     [ 'Allentown',
       'Altoona',
       'Bethlehem',
       'Erie',
       'Harrisburg',
       'Lancaster',
       'Philadelphia',
       'Pittsburgh',
       'Reading',
       'Scranton',
       'State College',
       'Wilkes-Barre',
       'York' ] },
  { name: 'Rhode Island',
    children:
     [ 'Cranston',
       'East Providence',
       'Pawtucket',
       'Providence',
       'Warwick',
       'Woonsocket' ] },
  { name: 'South Carolina',
    children:
     [ 'Charleston',
       'Columbia',
       'Florence',
       'Goose Creek',
       'Greenville',
       'Hilton Head Island',
       'Mount Pleasant',
       'North Charleston',
       'Rock Hill',
       'Spartanburg',
       'Summerville',
       'Sumter' ] },
  { name: 'South Dakota',
    children: [ 'Rapid City', 'Sioux Falls' ] },
  { name: 'Tennessee',
    children:
     [ 'Bartlett',
       'Brentwood',
       'Chattanooga',
       'Clarksville',
       'Cleveland',
       'Collierville',
       'Franklin',
       'Germantown',
       'Hendersonville',
       'Jackson',
       'Johnson City',
       'Kingsport',
       'Knoxville',
       'Memphis',
       'Murfreesboro',
       'Nashville-Davidson',
       'Smyrna' ] },
  { name: 'Texas',
    children:
     [ 'Abilene',
       'Allen',
       'Amarillo',
       'Arlington',
       'Austin',
       'Baytown',
       'Beaumont',
       'Bedford',
       'Brownsville',
       'Bryan',
       'Burleson',
       'Carrollton',
       'Cedar Hill',
       'Cedar Park',
       'College Station',
       'Conroe',
       'Coppell',
       'Corpus Christi',
       'Dallas',
       'DeSoto',
       'Denton',
       'Duncanville',
       'Edinburg',
       'El Paso',
       'Euless',
       'Flower Mound',
       'Fort Worth',
       'Friendswood',
       'Frisco',
       'Galveston',
       'Garland',
       'Georgetown',
       'Grand Prairie',
       'Grapevine',
       'Haltom City',
       'Harlingen',
       'Houston',
       'Huntsville',
       'Hurst',
       'Irving',
       'Keller',
       'Killeen',
       'Lancaster',
       'Laredo',
       'League City',
       'Lewisville',
       'Longview',
       'Lubbock',
       'Mansfield',
       'McAllen',
       'McKinney',
       'Mesquite',
       'Midland',
       'Mission',
       'Missouri City',
       'New Braunfels',
       'North Richland Hills',
       'Odessa',
       'Pasadena',
       'Pearland',
       'Pflugerville',
       'Pharr',
       'Plano',
       'Port Arthur',
       'Richardson',
       'Rockwall',
       'Round Rock',
       'Rowlett',
       'San Angelo',
       'San Antonio',
       'San Marcos',
       'Sherman',
       'Sugar Land',
       'Temple',
       'Texarkana',
       'Texas City',
       'The Colony',
       'Tyler',
       'Victoria',
       'Waco',
       'Weslaco',
       'Wichita Falls',
       'Wylie' ] },
  { name: 'Utah',
    children:
     [ 'Bountiful',
       'Draper',
       'Layton',
       'Lehi',
       'Logan',
       'Murray',
       'Ogden',
       'Orem',
       'Provo',
       'Riverton',
       'Roy',
       'Salt Lake City',
       'Sandy',
       'South Jordan',
       'Spanish Fork',
       'St. George',
       'Taylorsville',
       'West Jordan',
       'West Valley City' ] },
  { name: 'Vermont', children: [ 'Burlington' ] },
  { name: 'Virginia',
    children:
     [ 'Alexandria',
       'Blacksburg',
       'Charlottesville',
       'Chesapeake',
       'Danville',
       'Hampton',
       'Harrisonburg',
       'Leesburg',
       'Lynchburg',
       'Manassas',
       'Newport News',
       'Norfolk',
       'Portsmouth',
       'Richmond',
       'Roanoke',
       'Suffolk',
       'Virginia Beach' ] },
  { name: 'Washington',
    children:
     [ 'Auburn',
       'Bellevue',
       'Bellingham',
       'Bremerton',
       'Burien',
       'Edmonds',
       'Everett',
       'Federal Way',
       'Kennewick',
       'Kent',
       'Kirkland',
       'Lacey',
       'Lakewood',
       'Marysville',
       'Olympia',
       'Pasco',
       'Puyallup',
       'Redmond',
       'Renton',
       'Richland',
       'Sammamish',
       'Seattle',
       'Shoreline',
       'Spokane',
       'Spokane Valley',
       'Tacoma',
       'Vancouver',
       'Yakima' ] },
  { name: 'West Virginia',
    children: [ 'Charleston', 'Huntington' ] },
  { name: 'Wisconsin',
    children:
     [ 'Appleton',
       'Beloit',
       'Brookfield',
       'Eau Claire',
       'Fond du Lac',
       'Green Bay',
       'Greenfield',
       'Janesville',
       'Kenosha',
       'La Crosse',
       'Madison',
       'Milwaukee',
       'New Berlin',
       'Oshkosh',
       'Racine',
       'Sheboygan',
       'Waukesha',
       'Wausau',
       'Wauwatosa',
       'West Allis' ] },
  { name: 'Wyoming', children: [ 'Casper', 'Cheyenne' ] }
]
